# Generated by Django 3.2.8 on 2021-10-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('neighbourhood', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('suggestion', models.TextField(max_length=250)),
            ],
        ),
    ]
